name: ci-cd

on:
  push:
    branches:
      - '**/*'
  pull_request:
  release:
    types: [released]
env:
  NODE_PUBLISH_INSTALL_VERSION: 14
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [14, 16, 18, 19]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Install NPM Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run jest
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage/
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: unit
    if: github.event_name == 'release'
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node ${{ env.NODE_PUBLISH_INSTALL_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_PUBLISH_INSTALL_VERSION }}
      - name: Install NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Install NPM Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
